#!/bin/bash
# Version 1: 3-chip SNN MNIST demo (pre-computed spike traffic)
#
# Pipeline:
#   chip0 (input  784 neurons) ──spikes──> chip1 (hidden 256 neurons)
#   chip1 (hidden 256 neurons) ──spikes──> chip2 (output  10 neurons)
#
# Traffic source: mnist_snn_traffic.txt (pre-generated by gen_mnist_traffic.py)
#   - chip0->chip1: 7273 spike packets
#   - chip1->chip2: 1758 spike packets
#   - 10 images × 8 timesteps × interval=500 cycles, max inject_cycle=40000
#
# Each chip runs as a separate noxim process (multi-process FileIO mode).
# All three processes start simultaneously and run in parallel.
#
# Note:
#   In pre-computed traffic mode, FileIO crossOutThread now dumps all
#   src_chip-matching records to chipX_out at startup (while preserving each
#   record's inject_cycle). The receiver side still injects by inject_cycle.
#   This avoids wall-clock skew across processes causing late records to be
#   missed by a faster receiver.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="$SCRIPT_DIR/../bin"           # noxim binary + power.yaml live here
NOXIM="$BIN_DIR/noxim"
CONFIG="$SCRIPT_DIR/../config_examples/default_config.yaml"
TRAFFIC="$SCRIPT_DIR/../traffic_tables/mnist_snn_traffic.txt"
OUTDIR="$SCRIPT_DIR/../results/snn_v1_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$OUTDIR"

export CONDA_PREFIX=/home/st1101/miniconda3/envs/paper
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

# noxim looks for power.yaml in CWD; run each process from bin/
run_chip() { cd "$BIN_DIR" && exec "$@"; }

# --- expected packet counts (from traffic table header) ---
EXPECTED_01=7273   # chip0->chip1 packets
EXPECTED_12=1758   # chip1->chip2 packets

# --- IPC file wiring ---
# chip0_out -> chip1_in   chip1_out -> chip2_in   chip2_out -> chip0_in
CHIP0_OUT="$OUTDIR/chip0_out.txt"
CHIP1_OUT="$OUTDIR/chip1_out.txt"
CHIP2_OUT="$OUTDIR/chip2_out.txt"
touch "$CHIP0_OUT" "$CHIP1_OUT" "$CHIP2_OUT"

# --- simulation parameters ---
# reset_time=1000 (from yaml); last spike at cycle 40000
# -> sim must run past 40000 after reset; use 41000 for margin
SIM_CYCLES=41000
WARMUP=1000

echo "======================================================="
echo "  SNN Version 1: Pre-computed Spike Traffic (3 chips)"
echo "======================================================="
echo "Traffic file : $TRAFFIC"
echo "Results dir  : $OUTDIR"
echo "Sim cycles   : $SIM_CYCLES  (+ 1000 reset)"
echo ""

WALL_START=$(date +%s%N)

# --- launch chip 0 (input layer) ---
( run_chip "$NOXIM" -config "$CONFIG" \
    -chip_id 0 \
    -in_fifo   "$CHIP2_OUT" \
    -out_fifo  "$CHIP0_OUT" \
    -cross_traffic "$TRAFFIC" \
    -sim $SIM_CYCLES -warmup $WARMUP ) \
    > "$OUTDIR/chip0.log" 2>&1 &
PID0=$!

# --- launch chip 1 (hidden layer) ---
( run_chip "$NOXIM" -config "$CONFIG" \
    -chip_id 1 \
    -in_fifo   "$CHIP0_OUT" \
    -out_fifo  "$CHIP1_OUT" \
    -cross_traffic "$TRAFFIC" \
    -sim $SIM_CYCLES -warmup $WARMUP ) \
    > "$OUTDIR/chip1.log" 2>&1 &
PID1=$!

# --- launch chip 2 (output layer) ---
( run_chip "$NOXIM" -config "$CONFIG" \
    -chip_id 2 \
    -in_fifo   "$CHIP1_OUT" \
    -out_fifo  "$CHIP2_OUT" \
    -cross_traffic "$TRAFFIC" \
    -sim $SIM_CYCLES -warmup $WARMUP ) \
    > "$OUTDIR/chip2.log" 2>&1 &
PID2=$!

echo "Launched:  chip0 PID=$PID0  chip1 PID=$PID1  chip2 PID=$PID2"
echo "Running in parallel..."

wait $PID0; RC0=$?
wait $PID1; RC1=$?
wait $PID2; RC2=$?

WALL_END=$(date +%s%N)
WALL_MS=$(( (WALL_END - WALL_START) / 1000000 ))

echo "All processes finished. Wall-clock time: ${WALL_MS} ms"
echo ""

# --- extract and display FileIO stats ---
extract_stat() {
    local log=$1 key=$2
    grep "$key" "$log" | grep -oP '\d+' | head -1
}

TX0=$(extract_stat "$OUTDIR/chip0.log" "Packets written to out_fifo")
TX1=$(extract_stat "$OUTDIR/chip1.log" "Packets written to out_fifo")
TX2=$(extract_stat "$OUTDIR/chip2.log" "Packets written to out_fifo")
RX0=$(extract_stat "$OUTDIR/chip0.log" "Flits read from in_fifo")
RX1=$(extract_stat "$OUTDIR/chip1.log" "Flits read from in_fifo")
RX2=$(extract_stat "$OUTDIR/chip2.log" "Flits read from in_fifo")

echo "------- FileIO Traffic Summary -------"
printf "%-8s  %-20s  %-20s\n" "Chip" "Packets sent (out)" "Flits received (in)"
printf "%-8s  %-20s  %-20s\n" "chip0"  "${TX0:-?}" "${RX0:-?}"
printf "%-8s  %-20s  %-20s\n" "chip1"  "${TX1:-?}" "${RX1:-?}"
printf "%-8s  %-20s  %-20s\n" "chip2"  "${TX2:-?}" "${RX2:-?}"
echo ""

echo "------- Verification -------"
OK=1
check() {
    local label=$1 got=$2 expected=$3
    if [ "${got:-0}" -eq "$expected" ] 2>/dev/null; then
        echo "  [PASS] $label: $got == $expected"
    else
        echo "  [FAIL] $label: got=${got:-?}  expected=$expected"
        OK=0
    fi
}
check "chip0 TX (->chip1 packets)" "$TX0" "$EXPECTED_01"
check "chip1 TX (->chip2 packets)" "$TX1" "$EXPECTED_12"
check "chip1 RX flits (from chip0)" "$RX1" $(( EXPECTED_01 * 2 ))
check "chip2 RX flits (from chip1)" "$RX2" $(( EXPECTED_12 * 2 ))
echo ""

# --- NoC performance summary from each chip log ---
echo "------- NoC Performance -------"
for chip in 0 1 2; do
    log="$OUTDIR/chip${chip}.log"
    delay=$(grep "Global average delay" "$log" | grep -oP '[\d.]+' | head -1)
    thru=$( grep "Network throughput"   "$log" | grep -oP '[\d.]+' | head -1)
    energy=$(grep "Total energy"        "$log" | grep -oP '[\d.e+-]+' | head -1)
    echo "  chip${chip}:  avg_delay=${delay:-?} cycles  throughput=${thru:-?} flits/cycle  energy=${energy:-?} J"
done
echo ""

if [ $RC0 -ne 0 ] || [ $RC1 -ne 0 ] || [ $RC2 -ne 0 ]; then
    echo "WARNING: exit codes: chip0=$RC0 chip1=$RC1 chip2=$RC2"
fi

[ "$OK" -eq 1 ] && echo "All checks PASSED." || echo "Some checks FAILED — see logs in $OUTDIR/"
echo "Full logs: $OUTDIR/"
